jwt:
  private.key: classpath:app.key

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': #拦截的请求
            allowedOrigins:       #可跨域的网站
            allowedMethods:
            allowedHeaders: '*' #允许携带的头信息
            allowCredentials: true #是否允许带cookie
            maxAge: 36000 #跨域检测的有效期

      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**

        - id: inform
          uri: lb://inform
          predicates:
            - Path=/inform/**

        - id: schedule
          uri: lb://schedule
          predicates:
            - Path=/schedule/**

        - id: transaction
          uri: lb://transaction
          predicates:
            - Path=/transaction/**


      default-filters:
        - StripPrefix=1
server:
  port: 20030
