spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://8.130.8.90:3306/t1?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  data:
    mongodb:
      uri: mongodb://clwlc:123456@8.130.8.90:27017/?authSource=admin
      database: test
      authentication-database: admin

  application:
    name: dbAccess
  cloud:
    nacos:
      server-addr: localhost:8848

