spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.220.1/clwlc?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  data:
    mongodb:
      uri: mongodb://clwlc:123456@192.168.220.1:27020/clwlc
      database: clwlc
#      authentication-database: admin

  application:
    name: dbAccess
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: 192.168.220.1
    port: 6379

server:
  port: 20000

