spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456a
    url: jdbc:mysql://192.168.220.129/clwlc?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


  data:
    mongodb:
      uri: mongodb://clwlc:123456@192.168.220.129:27017/clwlc
#      host: '@mongoIp@'
#      port: 27017
#      username: clwlc
#      password:
#        - 123456
#      database: clwlw
#      authentication-database: admin

  application:
    name: dbAccess
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: '@redisIp@'
    port: 6379

server:
  port: 20000

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
