spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.80.128/project?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


  application:
    name: Transaction
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: 192.168.220.1
    port: 6379

server:
  port: 20000
