feign:
  client:
    config:
      default:
        loggerLevel: BASIC

  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50


spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true

  redis:
    host: 192.168.220.1
    port: 6379

